-- Tabelle für Bewerbungen erstellen
create table bewerbungen (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  unternehmen text,
  richtung text not null,
  stadt text not null,
  datum date not null,
  status text not null default 'ausstehend' check (status in ('ausstehend', 'zusage', 'absage', 'email_senden')),
  link text,
  notizen text,
  email text,
  ansprechperson text
);

-- Falls die Tabelle bereits existiert, Spalten und Status nachträglich hinzufügen:
-- alter table bewerbungen add column if not exists notizen text;
-- alter table bewerbungen add column if not exists email text;
-- alter table bewerbungen add column if not exists ansprechperson text;
-- alter table bewerbungen drop constraint if exists bewerbungen_status_check;
-- alter table bewerbungen add constraint bewerbungen_status_check check (status in ('ausstehend', 'zusage', 'absage', 'email_senden'));

-- Öffentlicher Zugriff (kein Login nötig)
alter table bewerbungen enable row level security;

create policy "Alle können lesen" on bewerbungen
  for select using (true);

create policy "Alle können einfügen" on bewerbungen
  for insert with check (true);

create policy "Alle können updaten" on bewerbungen
  for update using (true);

create policy "Alle können löschen" on bewerbungen
  for delete using (true);
